name: Podcast Automation

on:
  workflow_dispatch:
  issues:
    types:
      - labeled

jobs:
  automation:
    if: |
      github.event.issue.title == 'New Video' && 
      contains(github.event.issue.labels.*.name, 'New Video')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run automation script
        env:
          API_KEY: ${{ secrets.YOUR_YOUTUBE_API_KEY }}
        run: |
          python scripts/automation_script.py

      - name: Commit changes
        run: |
          git config --global user.name '${{ secrets.MAIN_USERNAME }}'
          git config --global user.email '${{ secrets.MAIN_EMAIL }}'
          git add .
          git commit -m "New Podcast"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload RSS Feed
        uses: actions/upload-artifact@v3
        with:
          name: rss-feed
          path: rss_feed.xml

  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r archiver-requirements.txt

      - name: Archive Website
        run: |
          archiver --sitemaps https://kurakahani.github.io/sitemap.xml