name: Podcast Automation

on:
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install FFmpeg and git lfs
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run automation script
        env:
          API_KEY: ${{ secrets.YOUR_YOUTUBE_API_KEY }}
        run: |
          python scripts/automation_script.py

      - name: Commit changes
        run: |
          git config --global user.name '${{ secrets.MAIN_USERNAME }}'
          git config --global user.email '${{ secrets.MAIN_EMAIL }}'
          git lfs track "*.m4a"
          git add .
          git commit -m "New Podcast"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
