name: Podcast Automation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run automation script
        env:
          API_KEY: ${{ secrets.YOUR_YOUTUBE_API_KEY }}
        run: |
          python scripts/automation_script.py

          - name: Commit changes
          run: |
            git config --global user.name '${{ secrets.MAIN_USERNAME }}'
            git config --global user.email '${{ secrets.MAIN_EMAIL }}'
            git add .
            git commit -m "New Podcast"
            git push
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
